export const AllData=[
    {
        key:1,
        title:"",
        text:"",
        image:require("../assets/All")
    },
    {
        key:2,
        title:"",
        text:"",
        image:require("../assets/All")
    },
    {
        key:3,
        title:"",
        text:"",
        image:require("../assets/All")
    },
    {
        key:4,
        title:"",
        text:"",
        image:require("../assets/All")
    },
    {
        key:5,
        title:"",
        text:"",
        image:require("../assets/All")
    },
    {
        key:6,
        title:"",
        text:"",
        image:require("../assets/All")
    }
]