export const CategoriesData=[
    {
        key:1,
        title:"Planets",
        image:require("../assets/categories/planets.jpg")
    },
    {
        key:2,
        title:"Black Holes",
        image:require("../assets/categories/blackholes.png")
    },
    {
        key:3,
        title:"Galaxies",
        image:require("../assets/categories/galaxies.jpg")
    },
    {
        key:4,
        title:"Multiverse",
        image:require("../assets/categories/multiverse.png")
    },
    {
        key:5,
        title:"Space Travel",
        image:require("../assets/categories/spacetravel.png")
    },
    {
        key:6,
        title:"Time Travel",
        image:require("../assets/categories/timetravel.png")
    },
    {
        key:7,
        title:"Stars",
        image:require("../assets/categories/stars.jpg")
    },
    {
        key:8,
        title:"Satellites",
        image:require("../assets/categories/satellites.jpg")
    },
    {
        key:9,
        title:"Asteroids",
        image:require("../assets/categories/asteroids.jpg")
    },
    {
        key:10,
        title:"Astronauts",
        image:require("../assets/categories/astronauts.jpg")
    }
]